## Análise de dados com Estimators do Tensorflow

In [76]:
import pandas as pd
base = pd.read_csv('Consumo_cerveja.csv')
base.head()

Data  Temperatura_Media_C  Temperatura_Minima_C  \
0  2015-01-01                27.30                  23.9   
1  2015-01-02                27.02                  24.5   
2  2015-01-03                24.82                  22.4   
3  2015-01-04                23.98                  21.5   
4  2015-01-05                23.82                  21.0   

   Temperatura_Maxima_C  Precipitacao_mm  Final_Semana  Consumo_cerveja_litros  
0                  32.5              0.0             0                   25461  
1                  33.5              0.0             0                   28972  
2                  29.9              0.0             1                   30814  
3                  28.6              1.2             1                   29799  
4                  28.3              0.0             0                   28900

In [77]:
base.columns

Index(['Data', 'Temperatura_Media_C', 'Temperatura_Minima_C',
       'Temperatura_Maxima_C', 'Precipitacao_mm', 'Final_Semana',
       'Consumo_cerveja_litros'],
      dtype='object')

In [78]:
colunas_usadas = ['Temperatura_Media_C', 'Temperatura_Minima_C',
       'Temperatura_Maxima_C', 'Precipitacao_mm', 'Final_Semana',
       'Consumo_cerveja_litros']

In [79]:
colunas_usadas

['Temperatura_Media_C',
 'Temperatura_Minima_C',
 'Temperatura_Maxima_C',
 'Precipitacao_mm',
 'Final_Semana',
 'Consumo_cerveja_litros']

In [80]:
base = pd.read_csv('Consumo_cerveja.csv', usecols = colunas_usadas)

In [81]:
base.columns

Index(['Temperatura_Media_C', 'Temperatura_Minima_C', 'Temperatura_Maxima_C',
       'Precipitacao_mm', 'Final_Semana', 'Consumo_cerveja_litros'],
      dtype='object')

In [82]:
#Normalizando as colunas com dados numéricos
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['Temperatura_Media_C', 'Temperatura_Minima_C', 'Temperatura_Maxima_C',
       'Precipitacao_mm']] = scaler_x.fit_transform(base[['Temperatura_Media_C', 'Temperatura_Minima_C', 
                                                          'Temperatura_Maxima_C','Precipitacao_mm']])

In [83]:
base.head()

Temperatura_Media_C  Temperatura_Minima_C  Temperatura_Maxima_C  \
0             0.902256              0.956835              0.818182   
1             0.884712              1.000000              0.863636   
2             0.746867              0.848921              0.700000   
3             0.694236              0.784173              0.640909   
4             0.684211              0.748201              0.627273   

   Precipitacao_mm  Final_Semana  Consumo_cerveja_litros  
0         0.000000             0                   25461  
1         0.000000             0                   28972  
2         0.000000             1                   30814  
3         0.012658             1                   29799  
4         0.000000             0                   28900

In [84]:
#Normalizando a coluna previsora
scaler_y = MinMaxScaler()
base[['Consumo_cerveja_litros']] = scaler_y.fit_transform(base[['Consumo_cerveja_litros']])

In [85]:
base.head()

Temperatura_Media_C  Temperatura_Minima_C  Temperatura_Maxima_C  \
0             0.902256              0.956835              0.818182   
1             0.884712              1.000000              0.863636   
2             0.746867              0.848921              0.700000   
3             0.694236              0.784173              0.640909   
4             0.684211              0.748201              0.627273   

   Precipitacao_mm  Final_Semana  Consumo_cerveja_litros  
0         0.000000             0                0.471221  
1         0.000000             0                0.620031  
2         0.000000             1                0.698101  
3         0.012658             1                0.655082  
4         0.000000             0                0.616979

In [86]:
#Atribuindo os valor de X (inputs) e y(previsão)
X = base.drop('Consumo_cerveja_litros', axis = 1)
y = base.iloc[:, -1]

In [87]:
X

Temperatura_Media_C  Temperatura_Minima_C  Temperatura_Maxima_C  \
0               0.902256              0.956835              0.818182   
1               0.884712              1.000000              0.863636   
2               0.746867              0.848921              0.700000   
3               0.694236              0.784173              0.640909   
4               0.684211              0.748201              0.627273   
5               0.681704              0.683453              0.727273   
6               0.695489              0.640288              0.872727   
7               0.751880              0.640288              0.831818   
8               0.958647              0.812950              0.886364   
9               0.868421              0.827338              0.895455   
10              0.922306              0.834532              0.922727   
11              0.818296              0.776978              0.950000   
12              0.790727              0.762590              0.922727   
13              0.818296              0.769784              0.886364   
14              0.812030              0.784173              0.831818   
15              0.852130              0.841727              0.827273   
16              1.000000              0.820144              0.968182   
17              0.962406              0.920863              0.959091   
18              0.959900              0.870504              1.000000   
19              0.926065              0.913669              0.959091   
20              0.778195              0.870504              0.745455   
21              0.553885              0.618705              0.527273   
22              0.510025              0.568345              0.527273   
23              0.640351              0.604317              0.677273   
24              0.720551              0.539568              0.704545   
25              0.595238              0.597122              0.645455   
26              0.670426              0.712230              0.645455   
27              0.800752              0.683453              0.700000   
28              0.758145              0.784173              0.668182   
29              0.620301              0.741007              0.563636   
..                   ...                   ...                   ...   
335             0.576441              0.546763              0.677273   
336             0.597744              0.690647              0.527273   
337             0.617794              0.604317              0.663636   
338             0.745614              0.640288              0.731818   
339             0.640351              0.719424              0.613636   
340             0.447368              0.532374              0.427273   
341             0.551378              0.532374              0.613636   
342             0.692982              0.647482              0.609091   
343             0.695489              0.834532              0.600000   
344             0.697995              0.726619              0.718182   
345             0.690476              0.719424              0.740909   
346             0.729323              0.625899              0.750000   
347             0.838346              0.755396              0.818182   
348             0.799499              0.719424              0.831818   
349             0.572682              0.726619              0.468182   
350             0.652882              0.597122              0.645455   
351             0.847118              0.647482              0.863636   
352             0.679198              0.661871              0.763636   
353             0.622807              0.647482              0.659091   
354             0.640351              0.647482              0.663636   
355             0.733083              0.647482              0.813636   
356             0.912281              0.827338              0.813636   
357             0.740602              0.712230              0.772727   
358             0.669173              0.51798

In [88]:
y

0      0.471221
1      0.620031
2      0.698101
3      0.655082
4      0.616979
5      0.588073
6      0.652242
7      0.595660
8      0.446851
9      1.000000
10     0.928668
11     0.483174
12     0.536026
13     0.740951
14     0.482368
15     0.660973
16     0.989531
17     0.685810
18     0.632449
19     0.880902
20     0.626727
21     0.485378
22     0.315377
23     0.593583
24     0.709714
25     0.304188
26     0.662414
27     0.350089
28     0.354031
29     0.529880
         ...   
335    0.683564
336    0.595999
337    0.642960
338    0.767483
339    0.781427
340    0.382809
341    0.566669
342    0.542257
343    0.364076
344    0.694965
345    0.645757
346    0.629185
347    0.584386
348    0.604984
349    0.284776
350    0.423582
351    0.538230
352    0.771086
353    0.668984
354    0.444647
355    0.529160
356    0.513902
357    0.730228
358    0.507120
359    0.322624
360    0.761380
361    0.498093
362    0.337628
363    0.259558
364    0.343435
Name: Consumo_cerveja_li

In [89]:
type(X)

pandas.core.frame.DataFrame

In [90]:
type(y)

pandas.core.series.Series

In [91]:
#Colunas para o input
input_colunas = colunas_usadas[0:5]
input_colunas

['Temperatura_Media_C',
 'Temperatura_Minima_C',
 'Temperatura_Maxima_C',
 'Precipitacao_mm',
 'Final_Semana']

In [92]:
#Importando o tensorflow
import tensorflow as tf

In [93]:
colunas = [tf.feature_column.numeric_column(key = c) for c in input_colunas]

In [94]:
print(colunas[2])

NumericColumn(key='Temperatura_Maxima_C', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [95]:
#Separando em conjunto de treino e teste(30%) dos dados
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [96]:
X_treinamento.shape

(255, 5)

In [97]:
y_treinamento.shape

(255,)

In [98]:
X_teste.shape

(110, 5)

In [99]:
y_teste.shape

(110,)

In [100]:
#função de treinamento (input pandas) com lote de 32 registros e input aleatório dos dados
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [101]:
#função de teste  (input pandas) com lote de 32 registros e input em ordem dos dados
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                   batch_size = 32, num_epochs = 1000, shuffle = False)

In [102]:
#Criando o regressor linear com as colunas escolhidas
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\JSSICA~1\\AppData\\Local\\Temp\\tmpvppoh0u2', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001A698BD37B8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [106]:
#Treinamento do regressor com 1000 steps
regressor.train(input_fn=funcao_treinamento, steps = 1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JSSICA~1\AppData\Local\Temp\tmpvppoh0u2\model.ckpt-11000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 11000 into C:\Users\JSSICA~1\AppData\Local\Temp\tmpvppoh0u2\model.ckpt.
INFO:tensorflow:loss = 0.3819412, step = 11001
INFO:tensorflow:global_step/sec: 257.571
INFO:tensorflow:loss = 0.2264063, step = 11101 (0.388 sec)
INFO:tensorflow:global_step/sec: 362.473
INFO:tensorflow:loss = 0.36334705, step = 11201 (0.276 sec)
INFO:tensorflow:global_step/sec: 375.184
INFO:tensorflow:loss = 0.40814573, step = 11301 (0.267 sec)
INFO:tensorflow:global_step/sec: 375.179
INFO:tensorflow:loss = 0.35529718, step = 11401 (0.267 sec)
INFO:tensorflow:global_step/sec: 375.095
INFO:tensorflow:loss = 0.4646443, step = 11501 (0.282

In [107]:
#avaliação do treinamento
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-04-14T13:00:13Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JSSICA~1\AppData\Local\Temp\tmpvppoh0u2\model.ckpt-12000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [100/1000]
INFO:tensorflow:Evaluation [200/1000]
INFO:tensorflow:Evaluation [300/1000]
INFO:tensorflow:Evaluation [400/1000]
INFO:tensorflow:Evaluation [500/1000]
INFO:tensorflow:Evaluation [600/1000]
INFO:tensorflow:Evaluation [700/1000]
INFO:tensorflow:Evaluation [800/1000]
INFO:tensorflow:Evaluation [900/1000]
INFO:tensorflow:Evaluation [1000/1000]
INFO:tensorflow:Finished evaluation at 2019-04-14-13:00:16
INFO:tensorflow:Saving dict for global step 12000: average_loss = 0.009874497, global_step = 12000, label/mean = 0.47737056, loss = 0.3159839, prediction/mean = 0.47830808
INFO:tensorflow:Saving 'che

In [109]:
#Avaliação do teste
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-04-14T13:01:16Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JSSICA~1\AppData\Local\Temp\tmpvppoh0u2\model.ckpt-12000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [100/1000]
INFO:tensorflow:Evaluation [200/1000]
INFO:tensorflow:Evaluation [300/1000]
INFO:tensorflow:Evaluation [400/1000]
INFO:tensorflow:Evaluation [500/1000]
INFO:tensorflow:Evaluation [600/1000]
INFO:tensorflow:Evaluation [700/1000]
INFO:tensorflow:Evaluation [800/1000]
INFO:tensorflow:Evaluation [900/1000]
INFO:tensorflow:Evaluation [1000/1000]
INFO:tensorflow:Finished evaluation at 2019-04-14-13:01:19
INFO:tensorflow:Saving dict for global step 12000: average_loss = 0.009070632, global_step = 12000, label/mean = 0.44869664, loss = 0.29026023, prediction/mean = 0.43620846
INFO:tensorflow:Saving 'ch

In [110]:
metricas_treinamento

{'average_loss': 0.009874497,
 'label/mean': 0.47737056,
 'loss': 0.3159839,
 'prediction/mean': 0.47830808,
 'global_step': 12000}

In [111]:
metricas_teste

{'average_loss': 0.009070632,
 'label/mean': 0.44869664,
 'loss': 0.29026023,
 'prediction/mean': 0.43620846,
 'global_step': 12000}

In [112]:
#função de previsão utilizando os dados do teste
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [113]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [114]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JSSICA~1\AppData\Local\Temp\tmpvppoh0u2\model.ckpt-12000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.36498672], dtype=float32)},
 {'predictions': array([0.15526879], dtype=float32)},
 {'predictions': array([0.30945572], dtype=float32)},
 {'predictions': array([0.44205388], dtype=float32)},
 {'predictions': array([0.36499625], dtype=float32)},
 {'predictions': array([0.3902458], dtype=float32)},
 {'predictions': array([0.24413088], dtype=float32)},
 {'predictions': array([0.37716344], dtype=float32)},
 {'predictions': array([0.4442547], dtype=float32)},
 {'predictions': array([0.4179291], dtype=float32)},
 {'predictions': array([0.2612377], dtype=float32)},
 {'predictions': array([0.8592287], dtype=float32)},
 {'predictions': array([0.24306116], dtype=float32)},
 {'predictions': array([0.36604497], dtype=float32)},
 {'predictions': array([0.41619512], dtype=float32)},
 {'predictions': array([0.6452018], dtype=float32)},
 {'predictions': array([0.49907127], dtype=float32)},
 {'predictions': array([0.61708677], dtype=float32)},
 {'predictions': array([0.4476514]

In [115]:
#Listando os valores das previsões
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\JSSICA~1\AppData\Local\Temp\tmpvppoh0u2\model.ckpt-12000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [116]:
valores_previsoes

[array([0.36498672], dtype=float32),
 array([0.15526879], dtype=float32),
 array([0.30945572], dtype=float32),
 array([0.44205388], dtype=float32),
 array([0.36499625], dtype=float32),
 array([0.3902458], dtype=float32),
 array([0.24413088], dtype=float32),
 array([0.37716344], dtype=float32),
 array([0.4442547], dtype=float32),
 array([0.4179291], dtype=float32),
 array([0.2612377], dtype=float32),
 array([0.8592287], dtype=float32),
 array([0.24306116], dtype=float32),
 array([0.36604497], dtype=float32),
 array([0.41619512], dtype=float32),
 array([0.6452018], dtype=float32),
 array([0.49907127], dtype=float32),
 array([0.61708677], dtype=float32),
 array([0.4476514], dtype=float32),
 array([0.43265107], dtype=float32),
 array([0.27454478], dtype=float32),
 array([0.44709602], dtype=float32),
 array([0.46410668], dtype=float32),
 array([0.5231231], dtype=float32),
 array([0.7270954], dtype=float32),
 array([0.4776866], dtype=float32),
 array([0.43963978], dtype=float32),
 array([0.4

In [117]:
#Realizando reshape para transformar na escala inicial
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [118]:
valores_previsoes

array([[0.36498672],
       [0.15526879],
       [0.30945572],
       [0.44205388],
       [0.36499625],
       [0.3902458 ],
       [0.24413088],
       [0.37716344],
       [0.4442547 ],
       [0.4179291 ],
       [0.2612377 ],
       [0.8592287 ],
       [0.24306116],
       [0.36604497],
       [0.41619512],
       [0.6452018 ],
       [0.49907127],
       [0.61708677],
       [0.4476514 ],
       [0.43265107],
       [0.27454478],
       [0.44709602],
       [0.46410668],
       [0.5231231 ],
       [0.7270954 ],
       [0.4776866 ],
       [0.43963978],
       [0.46679676],
       [0.3274889 ],
       [0.2708128 ],
       [0.19578904],
       [0.37177762],
       [0.59260243],
       [0.2636346 ],
       [0.43236005],
       [0.21675324],
       [0.32200003],
       [0.59162736],
       [0.34547338],
       [0.38539317],
       [0.39304268],
       [0.6398284 ],
       [0.5734027 ],
       [0.35341817],
       [0.60871226],
       [0.7127723 ],
       [0.89022523],
       [0.266

In [119]:
#Retornando a escala inicial
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[22954.496],
       [18006.412],
       [21644.299],
       [24772.818],
       [22954.72 ],
       [23550.459],
       [20103.025],
       [23241.795],
       [24824.746],
       [24203.62 ],
       [20506.643],
       [34615.64 ],
       [20077.785],
       [22979.465],
       [24162.707],
       [29565.893],
       [26118.088],
       [28902.547],
       [24904.889],
       [24550.97 ],
       [20820.61 ],
       [24891.783],
       [25293.135],
       [26685.566],
       [31498.09 ],
       [25613.537],
       [24715.86 ],
       [25356.604],
       [22069.773],
       [20732.557],
       [18962.447],
       [23114.723],
       [28324.861],
       [20563.195],
       [24544.104],
       [19457.076],
       [21940.268],
       [28301.857],
       [22494.1  ],
       [23435.967],
       [23616.451],
       [29439.111],
       [27871.863],
       [22681.549],
       [28704.957],
       [31160.15 ],
       [35346.973],
       [20621.35 ],
       [22254.01 ],
       [25967.686],


In [120]:
y_teste.shape

(110,)

In [121]:
#Comparar as previsões realizadas com os dados de teste
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(110, 1)

In [122]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [123]:
y_teste2

array([[22162.],
       [19463.],
       [24215.],
       [28034.],
       [22634.],
       [22620.],
       [20824.],
       [25142.],
       [22356.],
       [26095.],
       [20238.],
       [36254.],
       [23210.],
       [21838.],
       [21281.],
       [26311.],
       [26249.],
       [32473.],
       [22933.],
       [20903.],
       [21406.],
       [23566.],
       [28397.],
       [26805.],
       [34382.],
       [24337.],
       [26308.],
       [26828.],
       [26275.],
       [19113.],
       [21454.],
       [24222.],
       [26389.],
       [21245.],
       [24258.],
       [17655.],
       [19525.],
       [25343.],
       [20738.],
       [24862.],
       [24529.],
       [32872.],
       [27030.],
       [19640.],
       [26362.],
       [35781.],
       [31836.],
       [17731.],
       [22821.],
       [30471.],
       [29637.],
       [31572.],
       [16977.],
       [22401.],
       [27387.],
       [27657.],
       [27582.],
       [30300.],
       [24876.

In [124]:
#Calculando o Erro Absoluto Médio e o Erro Quadrático Médio 
from sklearn.metrics import mean_absolute_error,mean_squared_error
mae = mean_absolute_error(y_teste2, valores_previsoes)
mse = mean_squared_error(y_teste2, valores_previsoes)

In [ ]:
mae